<script setup lang="ts">
import type { SettingsProfile } from '~/types/settings'
import UserAvatar from '~/components/ui/UserAvatar.vue'

const props = defineProps<{ profile: SettingsProfile }>()
const emit = defineEmits<{ (event: 'update:profile', value: SettingsProfile): void }>()
const update = (key: keyof SettingsProfile, value: string) => emit('update:profile', { ...props.profile, [key]: value })
</script>

<template><div class="flex flex-col gap-8 p-6 sm:p-8"><div><h3 class="mb-1 text-lg font-bold text-gray-900 dark:text-white">Profil public</h3><p class="text-sm text-gray-500 dark:text-gray-400">Ces informations seront visibles par les membres de votre équipe.</p></div><div class="flex items-center gap-6"><UserAvatar initials="AN" class="!h-20 !w-20 text-xl" /><div class="flex gap-3"><button class="rounded-xl bg-purple-600 px-4 py-2 text-sm font-bold text-white transition-colors hover:bg-purple-700">Changer l'avatar</button><button class="rounded-xl border border-gray-200 bg-gray-100 px-4 py-2 text-sm font-semibold text-gray-600 dark:border-gray-700 dark:bg-[#1b1a26] dark:text-gray-300">Supprimer</button></div></div><div class="grid grid-cols-1 gap-6 sm:grid-cols-2"><label class="flex flex-col gap-2 text-sm font-bold text-gray-700 dark:text-gray-300">Prénom<input :value="profile.firstName" class="settings-input" type="text" @input="update('firstName', ($event.target as HTMLInputElement).value)" /></label><label class="flex flex-col gap-2 text-sm font-bold text-gray-700 dark:text-gray-300">Nom<input :value="profile.lastName" class="settings-input" type="text" @input="update('lastName', ($event.target as HTMLInputElement).value)" /></label></div><label class="flex flex-col gap-2 text-sm font-bold text-gray-700 dark:text-gray-300">Adresse email<input :value="profile.email" class="settings-input" type="email" @input="update('email', ($event.target as HTMLInputElement).value)" /></label><label class="flex flex-col gap-2 text-sm font-bold text-gray-700 dark:text-gray-300">Biographie<textarea :value="profile.bio" rows="4" class="settings-input resize-none" @input="update('bio', ($event.target as HTMLTextAreaElement).value)" /><span class="text-xs font-normal text-gray-500 dark:text-gray-400">Brève description pour votre profil. Maximum 200 caractères.</span></label></div></template>
